[project]
name = "mcp-github"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "langchain-groq>=0.3.8",
    "mcp-use>=1.3.10",
    "mcp[cli]>=1.14.0",
]
